### ISSUE TITLE
Adding New Resource 

### ISSUE THREAD

**Issue by zurigo** [dev-mission/sfdreamer#57]
Button Not Submitting information when adding a new resource
<img width="1901" alt="Screen Shot 2021-08-13 at 3 26 11 PM" src="https://user-images.githubusercontent.com/25355168/129425099-34e34b7b-a347-4e4c-be5a-479d0b282446.png">

**Comment by francisli** [comment]
I think I may know what's happening... the Category drop down is being populated, but the initial value of the CategoryId is an empty string, which causes the submit to fail.

After we fetch the list of categories using the Api, we should check if the CategoryId is blank and set it to the first id in the list so that it matches the initial state of the dropdown.
